name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: install libsndfile
        run: sudo apt-get install -y libsndfile1

      - name: Install Tox
        run: pip install tox

      - name: Run Tox
        run: tox -e py

      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.python }}
          # use a wildcard so that the archives have a folder in the root
          path: .tox/py/cov_*
